language: node_js
node_js:
  - stable
  - '4.1'
  - '4.0'

notifications:
  email: false

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token:
      - secure: >-
          iodugg1i+wqxRqF3+kRVdL+yTnyNnWTbPI+OZ7AccLeKVgM8yEcJrgJD55EJ/q6HhTUBF439Y0QxRyFwXyqUHQcndm4Y/erRqHsniw/w4CdJgq9At7aXc7RyaSS5644LciTpq/Ml6E34wkYG0+udhJkVfTgW1OiawHunl01vcvw=

script:
  - npm run-script test-ci

after_script:
  - npm install -g codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov.info
