language: node_js
node_js:
  - stable
  - '4.1'
  - '4.0'

notifications:
  email: false

sudo: false

cache:
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token:
      - secure: >-
          iodugg1i+wqxRqF3+kRVdL+yTnyNnWTbPI+OZ7AccLeKVgM8yEcJrgJD55EJ/q6HhTUBF439Y0QxRyFwXyqUHQcndm4Y/erRqHsniw/w4CdJgq9At7aXc7RyaSS5644LciTpq/Ml6E34wkYG0+udhJkVfTgW1OiawHunl01vcvw=

before_script:
  - git clone https://github.com/bookbrainz/bookbrainz-sql.git
  - psql -c 'CREATE DATABASE bookbrainz_test;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp"; CREATE SCHEMA musicbrainz; CREATE SCHEMA bookbrainz;' -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/musicbrainz.sql -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/schemas/bookbrainz.sql -d bookbrainz_test -U postgres
  - psql -f bookbrainz-sql/scripts/create_triggers.sql -d bookbrainz_test -U postgres
  - cp ./config/test.json.example ./config/test.json

script:
  - npm run-script test-ci

after_script:
  - npm install -g codeclimate-test-reporter && codeclimate-test-reporter < coverage/lcov.info
