version: '2'

services:
  
  bookbrainz:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "9099:9099"

  postgres:
    container-name: postgres
    image: postgres:9.5
    ports:
      - "5342:5342"

  elasticsearch:
    container-name: elasticsearch
    environment:
      SERVICE_9200_NAME: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    ports:
      - "9200:9200"

  redis:
    container-name: redis
    image: redis:3.2-alpine
    network_mode: "bridge"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
