version: '2'

services:
  consul:
    command: -server -bootstrap
    image: progrium/consul
    network_mode: "host"
    ports:
      - "8500:8500"

  registrator:
    command: -cleanup consul://127.0.0.1:8500
    image: gliderlabs/registrator:v7
    depends_on:
      - consul
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  git2consul:
    command: --endpoint 127.0.0.1 --port 8500 --config-file /etc/git2consul.d/config.json
    image: cimpress/git2consul
    restart: always
    depends_on:
      - consul
    network_mode: "host"
    volumes:
      - ../:/tmp/bookbrainz-site.git
      - ./git2consul:/etc/git2consul.d

  bookbrainz:
    build:
      context: ..
      dockerfile: ./Dockerfile
    network_mode: "host"
    ports:
      - "9099:9099"

  postgres-master:
    environment:
      SERVICE_5342_NAME: pgbouncer-master
    image: postgres:9.5
    network_mode: "host"
    ports:
      - "5342:5342"

  elasticsearch:
    environment:
      SERVICE_9200_NAME: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    ports:
      - "9200:9200"

  bookbrainz-redis:
    environment:
      SERVICE_6379_NAME: bookbrainz-redis
    image: redis:3.2-alpine
    network_mode: "bridge"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
