version: '3'

services:
  
  bookbrainz:
    container_name: bookbrainz-site
    command: npm start
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "9099:9099"
