version: '3'

services:

  postgres:
    container-name: postgres
    image: postgres:9.5
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookbrainz
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backups/latest.tar:/var/bookbrainz-db-backups/latest.tar

  postgres-restore-database:
    container-name: postgres-restore-database
    command: bunzip2 /var/bookbrainz/latest.tar.bz && pg_restore -h postgres -U postgres -e -C -O /var/bookbrainz/latest.tar -d postgres
    image: postgres:9.5
    user: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookbrainz
    volumes:
      - ./db_dumps/latest.tar.bz:/var/bookbrainz/latest.tar.bz
    depends_on:
      - postgres
    
