version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:9.5
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookbrainz
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./backups/latest.tar:/var/bookbrainz-db-backups/latest.tar

  elasticsearch:
    container_name: elasticsearch
    environment:
      SERVICE_9200_NAME: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    ports:
      - "9200:9200"

  redis:
    container_name: redis
    image: redis:3.2-alpine
    network_mode: "bridge"
    command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"