# Run ESLint with autofix

name: Lint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  # Disabling linting on pull requests until this issue is resolved:
  # https://github.com/wearerequired/lint-action/issues/13
  # pull_request:
  #  branches: [ master ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Also check out Lobes bootstrap theme submodule
          submodules: true
          
      - name: NPM install
        uses: bahmutov/npm-install@v1 

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Enable linters with auto-fix
          auto_fix: true
          eslint: true
